### ISSUE TITLE
Tracking issue for the Macos notification group

### ISSUE THREAD

**Issue by hkratz** [rust-lang/compiler-team#471]
The MCP for creating a Macos notification group (#470) was accepted. This issue tracks the progress on the steps for actually creating it (see [Rust Forge documentation](https://forge.rust-lang.org/compiler/notification-groups.html)).

Progress:
- [X] File a tracking issue in the [rust-lang/compiler-team] repository to collect your progress.
- [X] Create a PR against the [rust-lang/team] repository adding the notification group. ➡️ https://github.com/rust-lang/team/pull/670
- [ ] Configure the [rust-lang/rust] repository to accept triagebot commands for this group. 
- [ ] Create a PR for the rustc-dev-guide amending [the notification group section](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html) to mention your group.
- [ ] Create a sample PR for the [rust-lang/team] repository showing how one can add oneself. This will be referenced by your blog post to show people how to join.
- [ ] Create a Zulip stream for the notification group. If you don't have the permission to do, you can ask on [#t-compiler/wg-meta].
- [ ] Write an announcement blog post for Inside Rust and open a PR against [blog.rust-lang.org](https://github.com/rust-lang/blog.rust-lang.org).

**Comment by apiraino** [comment]
The notification group was created and documented on the rustc-dev-guide (as [Apple notification group](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html)). I think there is no dedicated Zulip stream but if the group wants one, they can always ask.

(In general [I don't see why](https://github.com/rust-lang/rust-forge/pull/820/files#diff-209c0b180fa706620adc67cda8c76209154c0e282150238ee63dd5ecc29b6121L20-L21) a new Zulip channel should the default when creating a notification group)
