### ISSUE TITLE
prepare for design meeting

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/compiler-team#59]
In our recent steering meeting, we made a decision to try and institute a design meeting. There is now some work to get ready for that.

## Meeting schedule

@michaelwoerister and I proposed a 4 week cycle with this general shape:

- Week 1 -- Scheduling meeting
- Week 2 -- Design meeting 1
- Week 3 -- Design meeting 2
- Week 4 -- Steering meeting (non-technical discussion)

The scheduling meeting would be used to decide the topics of the remaining 3 meetings.

## work items

- [ ] the compiler-team calendar needs to be updated to help us track the schedule
- [ ] we need a template for meeting proposals (nothing complex)
- [ ] we need a place to put those proposals (I propose we put them as PRs against this repository?)
- [ ] ultimately, we should have an RFC describing the change
