### ISSUE TITLE
Policy: no discussions on T-compiler tracking issues

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/compiler-team#739]
# Proposal

Tracking issues frequently become unmanageably large (see https://github.com/rust-lang/rust/issues?q=is%3Aopen+label%3AC-tracking-issue+sort%3Acomments-desc, where 25 issues have 99+ comments and 75 issues have 50+ comments, plus some extreme ones with hundreds of comments). It's a lot of effort to go through those issues and find specific discussion topics. Even if you have direct links to a specific comment, github starts hiding them.

I have started locking some tracking issues by default and asking people to take their discussions to zulip or separate issues. But, I have also made mistakes and suggested that all discussions must happen on zulip and github is only for issues, or forgot to leave a message about why I locked it entirely. And then we have over 700 tracking issues that do not follow this policy at all. Of course for most tracking issues, this never becomes a problem, but it's not clear to me that we can prevent the few for which it does become a problem.

Thus I am proposing to state that tracking issues with the T-compiler or T-lang label should not have discussions on them and any discussions will be deleted. Instead users should open a new github issue with the feature's `F-` label for specific topics and link back to the main tracking issue.

# Mentors or Reviewers

not applicable

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by nikomatsakis** [comment]
Big +1 to this.

Also I am amused by the fact that I'm violating the very policy I'm in favor of by leaving this comment. Sue me.
