### ISSUE TITLE
[Tracking Issue] RFC 3599 Reorganize the Compiler Team

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/compiler-team#757]
This is a tracking issue for the RFC "3599" (rust-lang/rfcs#3599).

**Steps:**

- [x] Implement the RFC (@davidtwco and @wesleywiser are working on this): https://github.com/rust-lang/team/pull/1585
- [x] blog.rust-lang.org post: https://github.com/rust-lang/blog.rust-lang.org/pull/1421
- [ ] Adjust compiler team documentation as appropriate 

**Unresolved questions:**

None currently

**Comment by davidtwco** [comment]
This is done now
