### ISSUE TITLE
Tracking Issue for the WASM | WASI | Emscripten notification groups

### ISSUE THREAD

**Issue by juntyr** [rust-lang/compiler-team#799]
Adapted from https://forge.rust-lang.org/compiler/notification-groups.html#notification-groups:

- [x] Propose the group by preparing a Major Change Proposal (MCP): https://github.com/rust-lang/compiler-team/issues/794
- [x] File a tracking issue in the rust-lang/compiler-team repository to collect your progress: https://github.com/rust-lang/compiler-team/issues/799
- [x] Create a PR against the rust-lang/team repository adding the notification group: https://github.com/rust-lang/team/pull/1578
- [x] Configure the rust-lang/rust repository to accept triagebot commands for this group: https://github.com/rust-lang/rust/pull/131875
- [x] Create a PR for the rustc-dev-guide amending [the notification group section](https://rustc-dev-guide.rust-lang.org/notification-groups/about.html) to mention your group: https://github.com/rust-lang/rustc-dev-guide/pull/2100
- [x] Create a sample PR for the rust-lang/team repository showing how one can add oneself. This will be referenced by your blog post to show people how to join: https://github.com/rust-lang/team/pull/1579, https://github.com/rust-lang/team/pull/1580, and https://github.com/rust-lang/team/pull/1581
- [x] Create a Zulip stream for the notification group: https://rust-lang.zulipchat.com/#narrow/stream/463513-t-compiler.2Fwasm
- [ ] Write an announcement blog post for Inside Rust and open a PR against [blog.rust-lang.org](https://github.com/rust-lang/blog.rust-lang.org).

**Comment by apiraino** [comment]
The blog post probably was never written, at this point we can just close this
